- name: set promt
  ansible.builtin.shell: set-hostname {{tool_name}}

- name: Download Hashicorp repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install vault
  ansible.builtin.yum:
    Name: vault
    state: installed

- name: cope hel file
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start vault service
  ansible.builtin.systemd_service:
  enabled: yes
  state: restarted